[build]
  functions = "netlify/functions"

[functions."snapshot-gameweek-background"]
  schedule = "@hourly"

[[redirects]]
  from = "/api/gameweek"
  to = "/.netlify/functions/gameweek"
  status = 200

[[redirects]]
  from = "/api/progress"
  to = "/.netlify/functions/progress"
  status = 200

[[redirects]]
  from = "/api/standings"
  to = "/.netlify/functions/standings"
  status = 200

[[redirects]]
  from = "/api/standings-live"
  to = "/.netlify/functions/standings-live"
  status = 200
