// One-time backfill data for GW1-3, transcribed from the league's own
// records. captainName gets matched against each club's 6 managers' real
// FPL player_name (case-insensitive). maxChip/noCaptain are special
// markers for weeks that weren't a plain manual pick.

module.exports = [
  // GW1
  { club: "Arsenal", event: 1, captainName: "Apurv Kulkarni" },
  { club: "Aston Villa", event: 1, captainName: "Jasprit Singh Sasan" },
  { club: "Bournemouth", event: 1, captainName: "Kiran Sreebal" },
  { club: "Brentford", event: 1, captainName: "Avnish Tripathy" },
  { club: "Brighton", event: 1, captainName: "Shubham Vechalekar" },
  { club: "Chelsea", event: 1, captainName: "Nihal Sawakhande" },
  { club: "Coventry City", event: 1, captainName: "Shivansh Gupta" },
  { club: "Crystal Palace", event: 1, captainName: "Tanmay Saini" },
  { club: "Everton", event: 1, captainName: "Riyaz Syed" },
  { club: "Fulham", event: 1, captainName: "Yashasva Tungare" },
  { club: "Hull City", event: 1, captainName: "Gau Mohanty" },
  { club: "Ipswich Town", event: 1, captainName: "Pranav Phadnis" },
  { club: "Leeds", event: 1, captainName: "Gaurav Khade" },
  { club: "Liverpool", event: 1, maxChip: true },
  { club: "Man City", event: 1, captainName: "Arpan Mathur" },
  { club: "Man Utd", event: 1, maxChip: true },
  { club: "Newcastle", event: 1, captainName: "Sameet Kode" },
  { club: "Nott'm Forest", event: 1, captainName: "V K" },
  { club: "Spurs", event: 1, captainName: "Abhiman Kotwal" },
  { club: "Sunderland", event: 1, captainName: "Shaibaz Khan" },

  // GW2
  { club: "Arsenal", event: 2, captainName: "Randhirsingh Nikam" },
  { club: "Aston Villa", event: 2, captainName: "Aditya Bagal" },
  { club: "Bournemouth", event: 2, captainName: "kishan k" },
  { club: "Brentford", event: 2, captainName: "Somnath Ghosh" },
  { club: "Brighton", event: 2, captainName: "Sanket Sumant" },
  { club: "Chelsea", event: 2, captainName: "Shakti khade" },
  { club: "Coventry City", event: 2, captainName: "Ahmed Godil" },
  { club: "Crystal Palace", event: 2, captainName: "Tanmay Saini" },
  { club: "Everton", event: 2, captainName: "Sree Dharan" },
  { club: "Fulham", event: 2, captainName: "Akshay Kulkarni" },
  { club: "Hull City", event: 2, captainName: "Swagat Das" },
  { club: "Ipswich Town", event: 2, captainName: "Cyrus Bamji" },
  { club: "Leeds", event: 2, captainName: "Shubham Ghare" },
  { club: "Liverpool", event: 2, captainName: "Amay Nikam" },
  { club: "Man City", event: 2, captainName: "Rahul Arora" },
  { club: "Man Utd", event: 2, captainName: "Nikhil Jethwani" },
  { club: "Newcastle", event: 2, captainName: "Rahul Swami" },
  { club: "Nott'm Forest", event: 2, captainName: "Abdul Hameed" },
  { club: "Spurs", event: 2, noCaptain: true },
  { club: "Sunderland", event: 2, captainName: "Saurabh Pimple" },

  // GW3
  { club: "Arsenal", event: 3, captainName: "Tanmay Jagdale" },
  { club: "Aston Villa", event: 3, captainName: "Sachchit Ranade" },
  { club: "Bournemouth", event: 3, captainName: "Akash K" },
  { club: "Brentford", event: 3, captainName: "Avnish Tripathy" },
  { club: "Brighton", event: 3, captainName: "Shounak Desai" },
  { club: "Chelsea", event: 3, captainName: "Jay Kolhatkar" },
  { club: "Coventry City", event: 3, captainName: "Ashwin Nair" },
  { club: "Crystal Palace", event: 3, captainName: "Shardul Sawant" },
  { club: "Everton", event: 3, captainName: "Satamitra Ghosh Dastidar" },
  { club: "Fulham", event: 3, captainName: "Vijit M" },
  { club: "Hull City", event: 3, captainName: "Gau Mohanty" },
  { club: "Ipswich Town", event: 3, captainName: "Cyrus Bamji" },
  { club: "Leeds", event: 3, captainName: "Suhel Mulla" },
  { club: "Liverpool", event: 3, captainName: "Rohit Bhosale" },
  { club: "Man City", event: 3, captainName: "Nikhil Chandra" },
  { club: "Man Utd", event: 3, captainName: "Rahul Nankani" },
  { club: "Newcastle", event: 3, captainName: "Samanyu K" },
  { club: "Nott'm Forest", event: 3, captainName: "Winning Speech" },
  { club: "Spurs", event: 3, captainName: "Darlane Diukar" },
  { club: "Sunderland", event: 3, captainName: "Saurabh Pimple" },
];
